# Generated by Django 3.1.3 on 2020-11-25 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0002_delete_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='MakePost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_title', models.CharField(max_length=100)),
                ('post_text', models.TextField()),
                ('post_img', models.ImageField(upload_to='')),
                ('post_user', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
